In [1]:
import pandas as pd
from io import StringIO

# Your CSV data as a multi-line string
data = """student_id,name,age,gender,marks_math,marks_science,marks_english,attendance_percent
1001,Alice,16,F,85,78,92,95.0
1002,Bob,17,M,67,74,70,88.5
1003,Carol,16,F,92,89,85,98.0
1004,David,18,M,56,60,58,72.0
1005,Eva,17,F,78,82,80,91.0
1006,Frank,16,M,45,50,48,65.5
1007,Grace,17,F,88,,90,96.0
1008,Henry,16,M,74,70,,85.0
1009,Irene,18,F,90,94,96,99.0
1010,John,17,M,,60,55,70.0
1011,Kim,16,F,82,78,79,89.0
1012,Leo,17,M,68,72,60,82.0
"""

# Load into DataFrame
df = pd.read_csv(StringIO(data))

print(df)

    student_id   name  age gender  marks_math  marks_science  marks_english  \
0         1001  Alice   16      F        85.0           78.0           92.0
1         1002    Bob   17      M        67.0           74.0           70.0
2         1003  Carol   16      F        92.0           89.0           85.0
3         1004  David   18      M        56.0           60.0           58.0
4         1005    Eva   17      F        78.0           82.0           80.0
5         1006  Frank   16      M        45.0           50.0           48.0
6         1007  Grace   17      F        88.0            NaN           90.0
7         1008  Henry   16      M        74.0           70.0            NaN
8         1009  Irene   18      F        90.0           94.0           96.0
9         1010   John   17      M         NaN           60.0           55.0
10        1011    Kim   16      F        82.0           78.0           79.0
11        1012    Leo   17      M        68.0           72.0           60.0

    attendance_percent
0                 95.0
1                 88.5
2                 98.0
3                 72.0
4                 91.0
5                 65.5
6                 96.0
7                 85.0
8                 99.0
9                 70.0
10                89.0
11                82.0

Load students.csv into a pandas DataFrame.

Print the DataFrame shape.

Show the first 5 rows (head()).

Set student_id as the DataFrame index and show head() again.

Show describe() for only the three marks columns (marks_math, marks_science, marks_english).

Hints: use pd.read_csv, df.shape, df.head(), df.set_index(...), and df[['col1','col2',...]].describe()

In [3]:
df.head()

,student_id,name,age,gender,marks_math,marks_science,marks_english,attendance_percent
0,1001,Alice,16,F,85.0,78.0,92.0,95.0
1,1002,Bob,17,M,67.0,74.0,70.0,88.5
2,1003,Carol,16,F,92.0,89.0,85.0,98.0
3,1004,David,18,M,56.0,60.0,58.0,72.0
4,1005,Eva,17,F,78.0,82.0,80.0,91.0

In [4]:
df.set_index("student_id", inplace = True)

In [5]:
print(df.head())
print(df[["marks_math", "marks_science", "marks_english"]].describe())

             name  age gender  marks_math  marks_science  marks_english  \
student_id
1001        Alice   16      F        85.0           78.0           92.0
1002          Bob   17      M        67.0           74.0           70.0
1003        Carol   16      F        92.0           89.0           85.0
1004        David   18      M        56.0           60.0           58.0
1005          Eva   17      F        78.0           82.0           80.0

            attendance_percent
student_id
1001                      95.0
1002                      88.5
1003                      98.0
1004                      72.0
1005                      91.0
       marks_math  marks_science  marks_english
count   11.000000      11.000000      11.000000
mean    75.000000      73.363636      73.909091
std     14.886235      13.055824      16.585865
min     45.000000      50.000000      48.000000
25%     67.500000      65.000000      59.000000
50%     78.000000      74.000000      79.000000
75%     86.500000      80.000000      87.500000
max     92.000000      94.000000      96.000000

Using the same DataFrame (df with student_id as index), 
calculate a new column called average_marks = mean of (marks_math, marks_science, marks_english) for each student.

Handle missing values by ignoring them (so if one subject is NaN, average over the remaining).

Print the updated DataFrame with only columns: name, marks_math, marks_science, marks_english, average_marks.

Using NumPy, find the student(s) whose average is close to 80 (use np.isclose with atol=1).

⚡ Hint: use df[['marks_math', ...]].mean(axis=1, skipna=True) for step 1.

In [27]:

df["average_marks"] = df[["marks_math", "marks_science", "marks_english"]].mean(axis = 1)

df

,name,age,gender,marks_math,marks_science,marks_english,attendance_percent,average_marks
student_id,,,,,,,,
1001,Alice,16,F,85.0,78.0,92.0,95.0,85.000000
1002,Bob,17,M,67.0,74.0,70.0,88.5,70.333333
1003,Carol,16,F,92.0,89.0,85.0,98.0,88.666667
1004,David,18,M,56.0,60.0,58.0,72.0,58.000000
1005,Eva,17,F,78.0,82.0,80.0,91.0,80.000000
1006,Frank,16,M,45.0,50.0,48.0,65.5,47.666667
1007,Grace,17,F,88.0,NaN,90.0,96.0,89.000000
1008,Henry,16,M,74.0,70.0,NaN,85.0,72.000000
1009,Irene,18,F,90.0,94.0,96.0,99.0,93.333333
1010,John,17,M,NaN,60.0,55.0,70.0,57.500000
1011,Kim,16,F,82.0,78.0,79.0,89.0,79.666667
1012,Leo,17,M,68.0,72.0,60.0,82.0,66.666667